import 'System'
import 'UnityEngine'
import 'Assembly-CSharp'	-- The user-code assembly generated by Unity

function Update()
	if Input.GetKey(KeyCode.Space) then
		GameObject.Instantiate(sphere, transform.position, Quaternion.identity)
	end
end