import 'System'
import 'UnityEngine'
import 'Assembly-CSharp'	-- The user-code assembly generated by Unity

function Start()
	-- `ExampleBehaviour` class is not in a namespace, which is 
	-- typical of C# scripts in Unity. This should successfully 
	-- resolve to a ProxyType as of NLua commit [dc976e8]
	Debug.Log(ExampleBehaviour) 
	Debug.Log(this:GetComponent('Transform'))
end